language: ruby
sudo: false
rvm:
  - ruby-head
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.2
os:
  - linux
  # - osx
before_script:
  - bundle install
script:
  - bundle exec middleman build
notifications:
  email: false
