language: ruby
sudo: false
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
os:
  - linux
  # - osx
before_script:
  - bundle install --no-deployment
script:
  - bundle exec middleman build
env:
  - CODECOV_TOKEN="13f0c9cb-6578-4281-b142-402106b16f2c"
notifications:
  email: false
