language: ruby
sudo: false
rvm:
  - ruby-head
#  - 2.5.0
#  - 2.4.3
#  - 2.3.6
#  - 2.2.9
  - 2.2
os:
  - linux
  # - osx
before_script:
  - bundle update --no-deployment
script:
  - bundle exec middleman build
env:
  - CODECOV_TOKEN="13f0c9cb-6578-4281-b142-402106b16f2c"
notifications:
  email: false
